/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class testJni */

#ifndef _Included_testJni
#define _Included_testJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     testJni
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_testJni_add
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
